---
new_page_extension: md
auto_deploy: false
admin_path: "/forestry/"
webhook_url: 
sections:
- type: directory
  path: src/fr/speakers
  label: Speakers FR
  create: documents
  match: "*.md"
upload_dir: src/assets/img
public_path: dist/img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
